const express = require("express");
const swaggerJSdoc = require("swagger-jsdoc");
const swaggerUI = require("swagger-ui-express");
const routes = require("./routes");

const options = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'api serverless node',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',
        },
        host: 'localhost:9000',
        basePath: '/',
        securityDefinitions: {
            bearerAuth: {
                type: 'apiKey',
                name: 'Authorization',
                scheme: 'bearer',
                in: 'header',
            }
        }
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/*.js'],
};
const specs = swaggerJSdoc(options);

const app = express();
app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(specs));
app.use("/", routes);

app.get('/swagger.json', (req, res) => {
    res.send(specs);
});

module.exports = app;